name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      FORCE_COLOR: 3
   
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm i -g snyk
      - run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - run: snyk monitor
      - run: snyk code test

      - name: install snyk-to-html
        run: |
          npm install snyk-to-html -g
          snyk test --json | snyk-to-html -o result.html
          mkdir downloads
          cp -v /home/runner/work/juice-shop/juice-shop/*.html /home/runner/work/juice-shop/juice-shop/downloads
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: downloads
